StringArrayDisplay/Models/ErrorViewModel.cs
using System;

namespace StringArrayDisplay.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StringArrayDisplay/ViewModels/StringsDisplayInfoViewModel.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace StringArrayDisplay.ViewModels
{
    public class StringsDisplayInfoViewModel : PageModel
    {
        public List<string> Strings;
        
        public int AvailableStringsCount;
        public int StringsPerPage;
    }
}

StringArrayDisplay/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StringArrayDisplay.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StringArrayDisplay.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StringArrayDisplay/Controllers/TextController.cs
using Microsoft.AspNetCore.Mvc;
using StringArrayDisplay.Data;
using System.Collections.Generic;
using StringArrayDisplay.ViewModels;
using static StringArrayDisplay.Data.Globals;
using static StringArrayDisplay.Auxiliary.ListHelper;

namespace StringArrayDisplay.Controllers
{
    public class TextController : Controller
    {
        private const int DefaultPageNumber = 1;
        private const int DefaultStringsPerPage = 3;

        private DataBase _dataBase;

        public TextController(DataBase dataBase)
        {
            _dataBase = dataBase;
        }
        
        public ActionResult Display(int? pageNumber, int? stringsPerPage)
        {
            TrySetDefaultValues(ref pageNumber, ref stringsPerPage);
            var castedStringsPerPage = (int) stringsPerPage;
            var castedPageNumber = (int) pageNumber;
            
            var availableStrings = _dataBase.GetAllStringsList();
            var displayedStrings = TryGetRangeWithOffsetOrLess(availableStrings, 
                GetFirstPageElementID(castedPageNumber, castedStringsPerPage), castedStringsPerPage);

            var viewModel = new StringsDisplayInfoViewModel
            {
                Strings = displayedStrings,
                AvailableStringsCount = availableStrings.Count,
                StringsPerPage = castedStringsPerPage
            };
            
            return View(viewModel);
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(string stringToAdd)
        {
            _dataBase.TryAddNewString(stringToAdd);
            return View();
        }

        #region Auxiliary Actions

        private int GetFirstPageElementID(int pageNumber, int stringsPerPage)
        {
            if (pageNumber == 1)
            {
                return 0;
            }

            return (pageNumber - 1) * stringsPerPage;
        }

        private void TrySetDefaultValues(ref int? pageNumber, ref int? stringsPerPage)
        {
            if (pageNumber == null)
            {
                pageNumber = DefaultPageNumber;
            }

            if (stringsPerPage == null)
            {
                stringsPerPage = DefaultStringsPerPage;
            }
        }

        #endregion
    }
}

StringArrayDisplay/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

StringArrayDisplay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StringArrayDisplay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap-sketchy.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StringArrayDisplay</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Text" asp-action="Display">Display</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Text" asp-action="Add">Add</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StringArrayDisplay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StringArrayDisplay/Views/Text/Add.cshtml
<body>
    <form method="post">
        <input type="text" value="str" name="stringToAdd" />
        <input type="submit" value="Добавить!" />
    </form>
</body>

StringArrayDisplay/Views/Text/Display.cshtml
@model StringArrayDisplay.ViewModels.StringsDisplayInfoViewModel

@{
    if (Model == null)
    {
        return;
    }

    // Display strings
    foreach (var selectedString in Model.Strings)
    {
        <br>
        @selectedString
    }
    
    // Display page numbers
    <br><br>
    var pagesCount = (float)Model.AvailableStringsCount / Model.StringsPerPage;
    for (int i = 1; i < pagesCount + 1; i++)
    {
        <a href="Display?pageNumber=@i&stringsPerPage=@Model.StringsPerPage">@i</a>
    }
}